name: Generate Stats Cards

on:
  schedule:
    - cron: "0 * * * *" # Atualiza a cada hora
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Stats SVG
        run: |
          mkdir -p dist
          # Este comando baixa a imagem diretamente da API oficial com seus parâmetros
          curl -o dist/github-stats.svg "https://github-readme-stats.vercel.app/api?username=crkautza&show_icons=true&theme=tokyonight&count_private=true&include_all_commits=true&hide_border=true"

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
